---
language: python
service: docker

# Use the new container infrastructure
sudo: false

env:
  global:
    - ROLE_NAME: ansible_couchbase
  matrix:
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian10

# Install ansible
addons:
  apt:
    packages:
    - python-pip

branches:
  only:
    - master

install:
  # Install ansible
  - pip install molecule yamllint ansible-lint docker

before_script:

  - cd ../
  - cd dt_digitalteam.$ROLE_NAME

script:
   - molecule test


notifications:
  email: tech@digitalteam.fr
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
