---
# Variable Setup
- name: Include OS-specific variables.
  include_vars: "{{ ansible_distribution }}.yml"

- name: Ensure all nodes are part of the Couchbase group
  fail: msg="Expected host to be part of the Couchbase group"
  when: "'couchbase' not in group_names"

- name: Set the Couchbase download path
  set_fact:
    couchbase_executable: "/tmp/couchbase-server.deb"

- name: Download Couchbase Server
  get_url:
    url: "{{ couchbase_debian_package_dl }}/{{ couchbase_debian_package }}"
    dest: "{{ couchbase_executable }}"

- name: Install Couchbase Server
  apt:
    deb: '{{ couchbase_executable }}'
    state: present

- name: Update all packages to the latest version
  apt:
    upgrade: 'yes'
    update_cache: true

- name: Create Couchbase path
  file:
    path: "{{ couchbase_path }}"
    state: directory
    recurse: true
    owner: couchbase
    group: couchbase
    mode: 0770

- name: Create Couchbase index path
  file:
    path: "{{ couchbase_index_path }}"
    state: directory
    recurse: true
    owner: couchbase
    group: couchbase
    mode: 0770

- name: Add Couchbase profile.d script
  copy: src=couchbase.sh dest=/etc/profile.d/couchbase.sh

- name: Wait for nodes to become active
  pause:
    seconds: 10

- include: cluster.yml
